name: Build and Publish Dev

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout kubernetes app
        uses: actions/checkout@v3
        with:
          repository: Paguelofacil/kubernetes-apps
          ref: dev
          path: .github/kubernetes-apps
          token: ${{ secrets.ACCESS_TOKEN_PF }}

      - name: AWS Login and Docker Build
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 702038983081.dkr.ecr.us-east-2.amazonaws.com
          docker build -t 702038983081.dkr.ecr.us-east-2.amazonaws.com/zero:dev-${{ github.run_number }} .
          docker push 702038983081.dkr.ecr.us-east-2.amazonaws.com/zero:dev-${{ github.run_number }}

      - name: Commit New Version
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo "New Docker Version dev-${{ github.run_number }}" > VERSION
          git add VERSION
          git commit -m "New Docker Version dev-${{ github.run_number }}"
          git push

      - name: Updating ArgoCD
        run: |
          cd .github/kubernetes-apps/zero
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          kustomize edit set image zero=702038983081.dkr.ecr.us-east-2.amazonaws.com/zero:dev-${{ github.run_number }}
          git add kustomization.yaml
          git commit -m "New Docker Version dev-${{ github.run_number }}"
          git push
